channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - bcalm=2.2.3
    - snakemake-minimal=6.4.0
    - screed>=1.0.5,<2
    - khmer=3.0.0a3
    - numpy
    - pytest=5.3.2
    - sortedcontainers=2.1.0
    - click=7.1.2
    - pyflakes
    - bbhash>=0.5.4
    - sourmash>=4.1.1,<5
    - pip
    - pip:
      - git+https://github.com/spacegraphcats/spacegraphcats@latest
    - r-tidyverse=1.3.1
    - r-tidygraph=1.2.0
    - r-irkernel
    - pandas=1.2.4
